// resources/js/components/feedback/RequirementProgress.vue
<template>
  <b-progress :max="100">
    <b-progress-bar v-for="(requirements, status_id) in groupedRequirements" :key="status_id" :class="`bg-${status(status_id).color} text-${status(status_id).contrastColor}`" :value="100. * (requirements.length) / total">
      {{ requirements.length }} {{ status(status_id).name }}
    </b-progress-bar>
  </b-progress>
</template>

<script>
import groupBy from 'lodash/groupBy'

export default {
  name: 'RequirementProgress',
  props: {
    requirements: { type: Array, required: true },
    statuses: { type: Array, required: true },
  },
  data() {
    return {}
  },
  computed: {
    total() {
      return this.requirements.length
    },
    groupedRequirements() {
      return groupBy(this.requirements, 'status_id')
    },
  },
  methods: {
    status(id) {
      return this.statuses.find(status => String(status.id) === String(id))
    }
  }
}
</script>

<style scoped>

</style>

// resources/js/components/print/feedback/RequirementProgress.jsx
import React from 'react'
import {View, Text} from '@react-pdf/renderer'
import groupBy from 'lodash/groupBy'
import colors from './colors.js'

const styles = {
    outer: {
        border: '1pt solid black',
        borderRadius: '2pt',
        lineHeight: 0.8,
        width: '100%',
        display: 'flex',
        flexDirection: 'row',
        marginBottom: '5mm',
    },
    bar: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    }
}

function RequirementProgress({ requirements, statuses }) {
    const groupedRequirements = groupBy(requirements, 'status_id')
    const countedStatuses = Object.entries(groupedRequirements).map(([statusId, requirements]) => {
        const status = statuses.find(status => status.id === parseInt(statusId)) || {}
        return { ...status, count: requirements.length }
    })
    return (
        <View style={styles.outer}>
            {countedStatuses.map(status => <View key={status.id} style={{
                ...styles.bar,
                flexBasis: status.count * 999999,
                backgroundColor: colors[status.color].color,
                color: colors[status.color].contrastColor
            }}>
                <Text>{ status.count } { status.name }</Text>
            </View>)}
        </View>
    )
}

export default RequirementProgress
